import React from 'react';
import { motion, AnimatePresence, type Variants } from 'framer-motion';
import { Sparkles, Mic } from 'lucide-react';
import type { SaarthiState } from './SaarthiContext';

export interface SaarthiAvatarProps {
  state?: SaarthiState;
  minimized?: boolean;
  onClick?: () => void;
  className?: string;
}

/**
 * Framer Motion Variant Map for Saarthi Digital Human Avatar Body
 */
export const saarthiAvatarVariants: Variants = {
  hidden: {
    opacity: 0,
    scale: 0.9,
    rotate: 0,
    y: 0,
  },
  enter: {
    opacity: 1,
    scale: 0.92,
    rotate: 0,
    y: 0,
    transition: {
      duration: 0.6,
      ease: [0.16, 1, 0.3, 1], // easeOutExpo
    },
  },
  greeting: {
    opacity: 1,
    scale: 1,
    rotate: [0, 10, 0], // Gentle 10-degree bow / hands joined gesture tilt
    y: [0, 4, 0],
    transition: {
      duration: 0.7,
      ease: [0.65, 0, 0.35, 1], // easeInOutCubic
    },
  },
  namaste: {
    opacity: 1,
    scale: [1, 0.92, 1.08, 1],
    rotate: [0, 8, -4, 0],
    y: [0, 6, -2, 0],
    transition: {
      duration: 1.5,
      ease: [0.65, 0, 0.35, 1],
    },
  },
  idle: {
    opacity: 1,
    scale: [1, 1.03, 1],
    y: [0, -5, 0],
    rotate: 0,
    transition: {
      duration: 3.8,
      repeat: Infinity,
      ease: 'easeInOut',
    },
  },
  listening: {
    opacity: 1,
    scale: 1.06,
    rotate: -3,
    transition: {
      duration: 1.2,
      repeat: Infinity,
      repeatType: 'reverse',
      ease: 'easeInOut',
    },
  },
  thinking: {
    opacity: 1,
    y: [-6, 6, -6],
    transition: {
      duration: 2.2,
      repeat: Infinity,
      ease: 'easeInOut',
    },
  },
  speaking: {
    opacity: 1,
    scale: [1, 1.05, 1.01, 1.04, 1],
    transition: {
      duration: 0.85,
      repeat: Infinity,
      ease: 'easeInOut',
    },
  },
  minimized: {
    scale: 0.46,
    opacity: 1,
    transition: {
      duration: 0.6,
      ease: [0.16, 1, 0.3, 1],
    },
  },
};

/**
 * SaarthiAvatar - Visual Shell for AI Conversational Agent Body
 *
 * Plug-and-play component: When the final SVG avatar sheets are generated by the design team,
 * only the inner SVG graphics inside this file will be updated.
 */
export const SaarthiAvatar: React.FC<SaarthiAvatarProps> = ({
  state = 'idle',
  minimized = false,
  onClick,
  className = '',
}) => {
  const variantKey = minimized ? 'minimized' : state;
  const size = minimized ? 64 : 140;

  const getGlowShadow = () => {
    switch (state) {
      case 'listening':
        return '0 0 45px rgba(52, 152, 219, 0.85), 0 0 90px rgba(238, 124, 43, 0.4)';
      case 'speaking':
        return '0 0 45px rgba(238, 124, 43, 0.85), 0 0 90px rgba(255, 196, 119, 0.45)';
      case 'thinking':
        return '0 0 35px rgba(155, 89, 182, 0.8), 0 0 70px rgba(255, 196, 119, 0.4)';
      case 'greeting':
      case 'namaste':
        return '0 0 55px rgba(238, 124, 43, 0.95), 0 0 110px rgba(255, 215, 0, 0.7)';
      default:
        return '0 0 28px rgba(238, 124, 43, 0.45), 0 0 60px rgba(217, 102, 32, 0.2)';
    }
  };

  return (
    <div
      className={`relative flex items-center justify-center cursor-pointer select-none ${className}`}
      onClick={onClick}
      role="button"
      tabIndex={0}
      aria-label={`Saarthi Avatar Body (${state} state)`}
      style={{ width: size, height: size }}
    >
      {/* Listening / Speaking Active Pulse Aura Ring */}
      <AnimatePresence>
        {(state === 'listening' || state === 'speaking') && (
          <motion.div
            initial={{ scale: 0.9, opacity: 0.7 }}
            animate={{ scale: [1, 1.4, 1.65], opacity: [0.7, 0.2, 0] }}
            exit={{ opacity: 0 }}
            transition={{ duration: 1.8, repeat: Infinity, ease: 'easeOut' }}
            className="absolute inset-0 rounded-full border-2 border-[#ee7c2b] pointer-events-none"
            style={{ width: size, height: size }}
          />
        )}
      </AnimatePresence>

      {/* Celestial Orbit Ring */}
      <motion.div
        animate={{ rotate: state === 'thinking' ? -360 : 360 }}
        transition={{ duration: state === 'thinking' ? 4 : 22, repeat: Infinity, ease: 'linear' }}
        className="absolute inset-[-1px] rounded-full border border-dashed border-[#ffc477]/30 pointer-events-none"
      />

      {/* Core Digital Human Avatar Placeholder Sphere */}
      <motion.div
        variants={saarthiAvatarVariants}
        initial="hidden"
        animate={variantKey}
        className="relative flex items-center justify-center rounded-full overflow-hidden shadow-2xl"
        style={{
          width: size,
          height: size,
          background: 'radial-gradient(circle at 35% 30%, #ffc477 0%, #ee7c2b 48%, #8f3d14 100%)',
          boxShadow: getGlowShadow(),
          transition: 'box-shadow 400ms ease',
        }}
      >
        {/* Sacred Om Emblem / Listening Visual */}
        <div className="relative z-10 flex items-center justify-center text-white drop-shadow-md">
          {state === 'listening' ? (
            <Mic size={minimized ? 32 : 70} className="text-amber-100 animate-pulse" />
          ) : state === 'thinking' ? (
            <Sparkles size={minimized ? 32 : 70} className="text-amber-200" />
          ) : (
            <span
              className="font-serif font-bold text-amber-50 select-none drop-shadow-xl flex items-center justify-center text-center leading-none"
              style={{
                fontSize: minimized ? '3rem' : '6.5rem',
                lineHeight: 1,
                transform: 'translateY(-2px)',
              }}
            >
              ॐ
            </span>
          )}
        </div>
      </motion.div>
    </div>
  );
};
